import { manifest, titleFromName, type Repo } from "@/lib/data";

/**
 * The project graph is a three-tier radial hierarchy:
 *
 *        root  ──▶  application node  ──▶  project node
 *      (1 core)      (16 tools used)       (301 repositories)
 *
 * The layout is computed here, deterministically, from data/manifest.json —
 * it is NOT a committed artifact. That is deliberate: an earlier version
 * baked a force-directed layout into data/graph.json, which meant the
 * positions could silently drift out of sync with the repository catalog
 * (and had to be regenerated by hand with Python + networkx). A closed-form
 * radial layout is cheap enough to compute at module load (~318 nodes of
 * trigonometry, once), always matches the manifest exactly, and — because
 * every random-looking offset comes from a seeded PRNG — is identical on the
 * server and the client, so there is no hydration mismatch to worry about.
 */

/** Deterministic PRNG (mulberry32) so "jitter" is stable across renders and environments. */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export type Vec3 = [number, number, number];

export interface AppNode {
  index: number;
  name: string;
  count: number;
  position: Vec3;
  color: string;
  /** Indices into `graph.projects` of every project that uses this application. */
  projectIndices: number[];
}

export interface ProjectNode {
  index: number;
  repoName: string;
  title: string;
  url: string;
  position: Vec3;
  /** Every application this project uses (5 of the 301 use two). */
  appIndices: number[];
  /** The application whose cluster this node is positioned in. */
  primaryApp: number;
  methods: string[];
  applicationRaw: string;
  sizeKb: number;
}

export interface GraphData {
  root: Vec3;
  applications: AppNode[];
  projects: ProjectNode[];
  /** Furthest distance of any node from the origin — used to frame the camera. */
  radius: number;
}

/**
 * One colour per application, ordered by repository count (descending), so the
 * busiest tools get the most legible tones. These are tuned to read as solid,
 * saturated chips against the light "porcelain" backdrop the graph stage
 * shares with the rest of the page — the core no longer drops to a dark
 * surface of its own, so every node colour has to hold up on the same near-
 * white ground as the site's cards and text.
 *
 * Colour is never the only channel: every application in the navigation
 * carries its own text label beside the dot, the popup names the project in
 * words, and the application hubs now carry their own name directly on the
 * node too.
 */
export const APP_COLORS: string[] = [
  "#2E8F68", // oxidised green — the accent, for the largest cluster
  "#2E7D7D", // teal
  "#5D9147", // sage
  "#3A7FA8", // slate blue
  "#A6772E", // ochre
  "#A85D40", // clay
  "#6F68A8", // muted violet
  "#3B9880", // mint
  "#5786BA", // periwinkle
  "#587D3A", // moss
  "#AD8038", // amber
  "#935F82", // dusty mauve
  "#45908C", // aqua
  "#838F3F", // olive
  "#6779AA", // dusk blue
  "#A16752", // terracotta
];

/**
 * The graph stage's own backdrop — the same porcelain the rest of the page
 * sits on, so the core reads as a continuation of the site rather than a
 * separate dark theater. It lives here, beside the node colours, rather than
 * in the scene component — the depth shell needs it to paint its backdrop,
 * and importing it from a three.js-dependent module would pull the whole 3D
 * bundle into the main chunk and defeat the scene's dynamic import.
 */
export const CORE_BACKDROP = "#F4F6F1";

const APP_RADIUS = 14;
const MIN_CLUSTER_RADIUS = 1.7;
const MAX_CLUSTER_RADIUS = 5.4;

/**
 * Evenly distributed point i of n on a unit sphere (Fibonacci / golden-angle
 * spiral). Gives a much more even spread than random spherical sampling, with
 * no clumping and no poles-heavy bias.
 */
function fibonacciSpherePoint(i: number, n: number): Vec3 {
  const offset = 2 / n;
  const increment = Math.PI * (3 - Math.sqrt(5)); // golden angle
  const y = i * offset - 1 + offset / 2;
  const r = Math.sqrt(Math.max(0, 1 - y * y));
  const phi = i * increment;
  return [Math.cos(phi) * r, y, Math.sin(phi) * r];
}

/**
 * Applications excluded from the graph entirely — a content decision, not a
 * data-quality fix. Mendeley's one repository is a reference manager
 * citation dump, not an investigation, and is dropped from both the
 * application list and the project set so no orphaned zero-project hub or
 * stray halo node is left behind. Exported so tests can assert the exclusion
 * directly instead of hardcoding a duplicate list to check against.
 */
export const EXCLUDED_APPLICATIONS = new Set<string>(["Mendeley"]);

function buildGraph(): GraphData {
  const repos = manifest.repos.filter(
    (repo) => !repo.applications.some((app) => EXCLUDED_APPLICATIONS.has(app)),
  );

  // Applications, most-used first — this order drives both the colour
  // assignment above and the order of the navigation buttons.
  const appNames = Object.keys(manifest.applicationTokenCounts)
    .filter((name) => !EXCLUDED_APPLICATIONS.has(name))
    .sort((a, b) => {
      const diff = (manifest.applicationTokenCounts[b] ?? 0) - (manifest.applicationTokenCounts[a] ?? 0);
      return diff !== 0 ? diff : a.localeCompare(b);
    });

  const appIndexByName = new Map<string, number>();
  appNames.forEach((name, i) => appIndexByName.set(name, i));

  const applications: AppNode[] = appNames.map((name, i) => {
    const dir = fibonacciSpherePoint(i, appNames.length);
    return {
      index: i,
      name,
      count: manifest.applicationTokenCounts[name] ?? 0,
      position: [dir[0] * APP_RADIUS, dir[1] * APP_RADIUS, dir[2] * APP_RADIUS] as Vec3,
      color: APP_COLORS[i % APP_COLORS.length] ?? "#4FB98A",
      projectIndices: [],
    };
  });

  // Group repositories by their primary (first-listed) application, so each
  // cluster's size is known before any position is computed.
  const membersByApp: Repo[][] = appNames.map(() => []);
  const unassigned: Repo[] = [];
  for (const repo of repos) {
    const primaryName = repo.applications[0];
    const primaryIndex = primaryName === undefined ? undefined : appIndexByName.get(primaryName);
    if (primaryIndex === undefined) {
      unassigned.push(repo);
      continue;
    }
    membersByApp[primaryIndex]?.push(repo);
  }

  const projects: ProjectNode[] = [];
  const random = mulberry32(0x5eed_301);

  appNames.forEach((_name, appIdx) => {
    const members = membersByApp[appIdx] ?? [];
    const app = applications[appIdx];
    if (!app || members.length === 0) return;

    // Cluster radius grows with the cube root of the member count so that
    // node density stays roughly constant whether a tool has 1 project or
    // 112 — then it is capped so neighbouring clusters stay distinguishable.
    const clusterRadius = Math.min(
      MAX_CLUSTER_RADIUS,
      Math.max(MIN_CLUSTER_RADIUS, 1.5 * Math.cbrt(members.length)),
    );

    members.forEach((repo, memberIdx) => {
      const dir = fibonacciSpherePoint(memberIdx, members.length);
      // Push each node onto a shell between 60% and 100% of the cluster
      // radius, so clusters read as small clouds rather than hollow shells.
      const shell = clusterRadius * (0.6 + 0.4 * random());
      const position: Vec3 = [
        app.position[0] + dir[0] * shell,
        app.position[1] + dir[1] * shell,
        app.position[2] + dir[2] * shell,
      ];

      const appIndices = repo.applications
        .map((a) => appIndexByName.get(a))
        .filter((v): v is number => v !== undefined);

      const projectIndex = projects.length;
      projects.push({
        index: projectIndex,
        repoName: repo.name,
        title: titleFromName(repo.name),
        url: repo.url,
        position,
        appIndices: appIndices.length > 0 ? appIndices : [appIdx],
        primaryApp: appIdx,
        methods: repo.methods,
        applicationRaw: repo.applicationRaw,
        sizeKb: repo.sizeKb,
      });
    });
  });

  // Any repository whose application token is not in the token list at all
  // (should be none, but the data is fetched live, so this stays safe) sits
  // in a loose halo rather than being silently dropped from the graph.
  unassigned.forEach((repo, i) => {
    const dir = fibonacciSpherePoint(i, Math.max(1, unassigned.length));
    const projectIndex = projects.length;
    projects.push({
      index: projectIndex,
      repoName: repo.name,
      title: titleFromName(repo.name),
      url: repo.url,
      position: [dir[0] * (APP_RADIUS + 6), dir[1] * (APP_RADIUS + 6), dir[2] * (APP_RADIUS + 6)],
      appIndices: [],
      primaryApp: -1,
      methods: repo.methods,
      applicationRaw: repo.applicationRaw,
      sizeKb: repo.sizeKb,
    });
  });

  // Back-reference: every application knows every project attached to it,
  // including the five projects that belong to two applications at once.
  for (const project of projects) {
    for (const appIdx of project.appIndices) {
      applications[appIdx]?.projectIndices.push(project.index);
    }
  }

  let radius = 0;
  for (const p of projects) {
    const d = Math.hypot(p.position[0], p.position[1], p.position[2]);
    if (d > radius) radius = d;
  }

  return { root: [0, 0, 0], applications, projects, radius };
}

export const graph: GraphData = buildGraph();

/** Flat [x,y,z, x,y,z, ...] pairs for the root→application spokes. */
export function rootEdgeVertices(): Float32Array {
  const out = new Float32Array(graph.applications.length * 6);
  graph.applications.forEach((app, i) => {
    out[i * 6 + 0] = graph.root[0];
    out[i * 6 + 1] = graph.root[1];
    out[i * 6 + 2] = graph.root[2];
    out[i * 6 + 3] = app.position[0];
    out[i * 6 + 4] = app.position[1];
    out[i * 6 + 5] = app.position[2];
  });
  return out;
}

/** Flat vertex pairs for every application→project edge, plus the app index each belongs to. */
export function projectEdgeVertices(): { positions: Float32Array; appIndexPerEdge: Int16Array } {
  const pairs: Array<[number, number]> = [];
  graph.projects.forEach((project) => {
    for (const appIdx of project.appIndices) pairs.push([appIdx, project.index]);
  });

  const positions = new Float32Array(pairs.length * 6);
  const appIndexPerEdge = new Int16Array(pairs.length);

  pairs.forEach(([appIdx, projectIdx], i) => {
    const app = graph.applications[appIdx];
    const project = graph.projects[projectIdx];
    if (!app || !project) return;
    positions[i * 6 + 0] = app.position[0];
    positions[i * 6 + 1] = app.position[1];
    positions[i * 6 + 2] = app.position[2];
    positions[i * 6 + 3] = project.position[0];
    positions[i * 6 + 4] = project.position[1];
    positions[i * 6 + 5] = project.position[2];
    appIndexPerEdge[i] = appIdx;
  });

  return { positions, appIndexPerEdge };
}

export function getApplication(index: number): AppNode | null {
  return graph.applications[index] ?? null;
}

export function getProject(index: number): ProjectNode | null {
  return graph.projects[index] ?? null;
}
